// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxescqmmmzhpqiimpdro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14ZXNjcW1tbXpocHFpaW1wZHJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NjUyMTcsImV4cCI6MjA2ODU0MTIxN30.Qi_HjGR96oT2n3U0in_gz9VqgBp-aK83pJb9btGDiMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});